version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: quotesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  python-app:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/quotesdb
    depends_on:
      - postgres

volumes:
  pg-data:
